sm-55 - create card component
svipulc/Evoke-ui pull request #7
Opened 2024-08-20 10:54 UTC by svipulc

# Pull Request: Card Component 

## Description

This pull request introduces a reusable Card component to our application. The Card component is designed to display content in a visually appealing and organized manner, with the ability to customize the header, content, and footer sections.

### Features

- **Flexible Structure**: The Card component allows for a header, content, and footer section, enabling users to organize their content effectively.

## Sample Image

### Default card
![DefaultCard](https://github.com/user-attachments/assets/da454367-87e4-4e27-a502-712b05ff7892)

### Post Card
![post card](https://github.com/user-attachments/assets/f5ae6d77-6033-4326-94a8-67911dd84668)

2024-08-28 08:40 UTC, kashyap27102 requested changes

2024-08-28 08:40 UTC, kashyap27102 commented on src/components/Card/index.style.tsx
Can you just remove the not needed part like
```js
{
    variants: {
      variant: {
        //variant
      },
      size: {
        //size
      },
    },
    defaultVariants: {
      //default variant
    },
  }
```
  or is it have meaning ?

2024-08-28 08:40 UTC, kashyap27102 commented on .storybook/main.ts
The commit includes alterations that do not align with the PR

2024-08-28 08:40 UTC, kashyap27102 commented on postcss.config.js
The commit includes alterations that do not align with the PR

2024-08-29 05:30 UTC, svipulc commented on .storybook/main.ts
this changes are done by eslint

2024-08-29 05:30 UTC, svipulc commented on postcss.config.js
this changes are done by eslint

2024-09-02 04:37 UTC, kashyap27102 approved these changes

2024-09-04 06:18 UTC, merged